/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    BracketMatchCard: typeof import('./src/components/BracketMatchCard.vue')['default']
    BracketView: typeof import('./src/components/BracketView.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    PlayerPanel: typeof import('./src/components/PlayerPanel.vue')['default']
    ProblemPanel: typeof import('./src/components/ProblemPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestResultsPanel: typeof import('./src/components/TestResultsPanel.vue')['default']
    WaitingLobby: typeof import('./src/components/WaitingLobby.vue')['default']
  }
}
